micromono:
  build: ./
  command: node /opt/index.js
  volumes:
    - ./:/opt
    - ../:/opt/micromono
    - ../:/opt/node_modules/micromono
  environment:
    - DEBUG=micromono*
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=warn

balancer:
  extends: micromono
  command: node /opt/balancer/server.js
  ports:
    - "3000:3000"
  links:
    - account
    - channel
    - home
    - io
  environment:
    - MICROMONO_SERVICE=account,channel,home,io

account:
  extends: micromono
  command: node /opt/account/index.js

channel:
  extends: micromono
  command: node /opt/channel/index.js

home:
  extends: micromono
  command: node /opt/home/index.js

io:
  extends: micromono
  command: node /opt/io/index.js

#
# nightwatch + selenium
#

balancer-istanbul:
  extends: micromono
  command: istanbul cover --config /opt/.istanbul.yml --dir /opt/balancer/coverage /opt/balancer/server.js
  ports:
    - "3000:3000"
  links:
    - account
    - home
    - io
  environment:
    - MICROMONO_SERVICE=account,home,io

account-istanbul:
  extends: micromono
  command: istanbul cover --config /opt/.istanbul.yml --dir /opt/account/coverage /opt/account/index.js

home-istanbul:
  extends: micromono
  command: istanbul cover --config /opt/.istanbul.yml --dir /opt/home/coverage /opt/home/index.js

io-istanbul:
  extends: micromono
  command: istanbul cover --config /opt/.istanbul.yml --dir /opt/io/coverage /opt/io/index.js

hub:
  image: selenium/hub:2.53.0
chrome:
  image: selenium/node-chrome:2.53.0
  links:
    - hub
    - balancer-istanbul
chromedebug:
  image: selenium/node-chrome-debug:2.53.0
  links:
    - hub
    - balancer
  ports:
    - "5900:5900"
firefox:
  image: selenium/node-firefox:2.53.0
  links:
    - hub
    - balancer-istanbul
firefoxdebug:
  image: selenium/node-firefox-debug:2.53.0
  links:
    - hub
    - balancer
  ports:
    - 5901:5900
nightwatch:
  image: blueimp/nightwatch:0.9
  links:
    - hub
  volumes:
    - ./test/e2e:/home/node
  environment:
    - APP_URL=http://balancer:3000


# NATS as service discovery backend

balancer-nats:
  extends: micromono
  command: node /opt/server.js --service account,home,io
  volumes:
    - ./balancer:/opt
  links:
    - account-nats
    - home-nats
    - io-nats
    - nats:nats.dev
  environment:
    - MICROMONO_DISCOVERY_BACKEND=nats
    - MICROMONO_DISCOVERY_NATS_SERVERS=nats://nats.dev:4222

nats:
  image: nats:0.7.2

account-nats:
  extends: account
  links:
    - nats:nats.dev
  environment:
    - MICROMONO_DISCOVERY_BACKEND=nats
    - MICROMONO_DISCOVERY_NATS_SERVERS=nats://nats.dev:4222

home-nats:
  extends: home
  links:
    - nats:nats.dev
  environment:
    - MICROMONO_DISCOVERY_BACKEND=nats
    - MICROMONO_DISCOVERY_NATS_SERVERS=nats://nats.dev:4222

io-nats:
  extends: io
  links:
    - nats:nats.dev
  environment:
    - MICROMONO_DISCOVERY_BACKEND=nats
    - MICROMONO_DISCOVERY_NATS_SERVERS=nats://nats.dev:4222

